//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: tools/un_resource.proto
namespace un_resource
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResBehaviorList")]
  public partial class ResBehaviorList : global::ProtoBuf.IExtensible
  {
    public ResBehaviorList() {}
    
    private readonly global::System.Collections.Generic.List<un_resource.ResBehavior> _list = new global::System.Collections.Generic.List<un_resource.ResBehavior>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<un_resource.ResBehavior> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResBehaviorTrans")]
  public partial class ResBehaviorTrans : global::ProtoBuf.IExtensible
  {
    public ResBehaviorTrans() {}
    
    private UNValueInt _from = new UNValueInt();
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"from", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int from
    {
      get { return _from.m_value; }
      set { _from.m_value = value; }
    }
    private UNValueInt _to = new UNValueInt();
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"to", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int to
    {
      get { return _to.m_value; }
      set { _to.m_value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResBehavior")]
  public partial class ResBehavior : global::ProtoBuf.IExtensible
  {
    public ResBehavior() {}
    
    private UNValueInt _ID = new UNValueInt();
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID.m_value; }
      set { _ID.m_value = value; }
    }
    private readonly global::System.Collections.Generic.List<un_resource.ResBehaviorTrans> _trans = new global::System.Collections.Generic.List<un_resource.ResBehaviorTrans>();
    [global::ProtoBuf.ProtoMember(2, Name=@"trans", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<un_resource.ResBehaviorTrans> trans
    {
      get { return _trans; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}