# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tools/un_resource.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tools/un_resource.proto',
  package='un_resource',
  serialized_pb=_b('\n\x17tools/un_resource.proto\x12\x0bun_resource\"9\n\x0fResBehaviorList\x12&\n\x04list\x18\x01 \x03(\x0b\x32\x18.un_resource.ResBehavior\",\n\x10ResBehaviorTrans\x12\x0c\n\x04\x66rom\x18\x01 \x02(\x05\x12\n\n\x02to\x18\x02 \x02(\x05\"G\n\x0bResBehavior\x12\n\n\x02ID\x18\x01 \x02(\x05\x12,\n\x05trans\x18\x02 \x03(\x0b\x32\x1d.un_resource.ResBehaviorTrans')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_RESBEHAVIORLIST = _descriptor.Descriptor(
  name='ResBehaviorList',
  full_name='un_resource.ResBehaviorList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='list', full_name='un_resource.ResBehaviorList.list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=97,
)


_RESBEHAVIORTRANS = _descriptor.Descriptor(
  name='ResBehaviorTrans',
  full_name='un_resource.ResBehaviorTrans',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='from', full_name='un_resource.ResBehaviorTrans.from', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='to', full_name='un_resource.ResBehaviorTrans.to', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=143,
)


_RESBEHAVIOR = _descriptor.Descriptor(
  name='ResBehavior',
  full_name='un_resource.ResBehavior',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='un_resource.ResBehavior.ID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='trans', full_name='un_resource.ResBehavior.trans', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=216,
)

_RESBEHAVIORLIST.fields_by_name['list'].message_type = _RESBEHAVIOR
_RESBEHAVIOR.fields_by_name['trans'].message_type = _RESBEHAVIORTRANS
DESCRIPTOR.message_types_by_name['ResBehaviorList'] = _RESBEHAVIORLIST
DESCRIPTOR.message_types_by_name['ResBehaviorTrans'] = _RESBEHAVIORTRANS
DESCRIPTOR.message_types_by_name['ResBehavior'] = _RESBEHAVIOR

ResBehaviorList = _reflection.GeneratedProtocolMessageType('ResBehaviorList', (_message.Message,), dict(
  DESCRIPTOR = _RESBEHAVIORLIST,
  __module__ = 'tools.un_resource_pb2'
  # @@protoc_insertion_point(class_scope:un_resource.ResBehaviorList)
  ))
_sym_db.RegisterMessage(ResBehaviorList)

ResBehaviorTrans = _reflection.GeneratedProtocolMessageType('ResBehaviorTrans', (_message.Message,), dict(
  DESCRIPTOR = _RESBEHAVIORTRANS,
  __module__ = 'tools.un_resource_pb2'
  # @@protoc_insertion_point(class_scope:un_resource.ResBehaviorTrans)
  ))
_sym_db.RegisterMessage(ResBehaviorTrans)

ResBehavior = _reflection.GeneratedProtocolMessageType('ResBehavior', (_message.Message,), dict(
  DESCRIPTOR = _RESBEHAVIOR,
  __module__ = 'tools.un_resource_pb2'
  # @@protoc_insertion_point(class_scope:un_resource.ResBehavior)
  ))
_sym_db.RegisterMessage(ResBehavior)


# @@protoc_insertion_point(module_scope)
